/*수강생 테이블*/
CREATE SEQUENCE SEQ_USER;

CREATE TABLE TBL_USER(
	USER_NUMBER NUMBER CONSTRAINT PK_USER PRIMARY KEY,
	USER_EMAIL VARCHAR(500),
	USER_PASSWORD VARCHAR(500),
	USER_NICKNAME VARCHAR(500),
	USER_PHONE_NUMBER VARCHAR2(500)
);
SELECT * FROM TBL_USER;


/*강사 테이블*/
CREATE SEQUENCE SEQ_TEACHER;

CREATE TABLE TBL_TEACHER(
	TEACHER_NUMBER NUMBER CONSTRAINT PK_TEACHER PRIMARY KEY,
	TEACHER_EMAIL VARCHAR(500),
	TEACHER_PASSWORD VARCHAR(500),
	TEACHER_NAME VARCHAR(500),
	TEACHER_BELONGING VARCHAR(500),
	TEACHER_PHONE_NUMBER VARCHAR2(500)
);


/*강의장 테이블*/
CREATE SEQUENCE SEQ_PLACE;

CREATE TABLE TBL_PLACE(
	PLACE_NUMBER NUMBER CONSTRAINT PK_PLACE PRIMARY KEY,
	PLACE_NAME VARCHAR(500),
	PLACE_ADDRESS VARCHAR(500),
	PLACE_MAXIMUM_NUMBER NUMBER,
	PLACE_DETAIL VARCHAR(500)
);

ALTER TABLE TBL_PLACE DROP COLUMN PLACE_DETAIL;
ALTER TABLE TBL_PLACE ADD PLACE_STATUS VARCHAR(500);

SELECT * FROM TBL_PLACE;


/*강의장 예약 테이블*/
CREATE SEQUENCE SEQ_RESERVE_PLACE;

CREATE TABLE TBL_RESERVE_PLACE(
	RESERVE_PLACE_NUMBER NUMBER CONSTRAINT PK_RESERVE_PLACE PRIMARY KEY,
	RESERVE_PLACE_DATE DATE,
	RESERVE_PLACE_MORNING CHAR(1),
	RESERVE_PLACE_AFTERNOON CHAR(1),
	RESERVE_PLACE_DINNER CHAR(1),
	PLACE_NUMBER NUMBER,
   CONSTRAINT FK_RESERVE_PLACE FOREIGN KEY (PLACE_NUMBER) REFERENCES TBL_PLACE(PLACE_NUMBER)
);




/*강의 테이블*/
CREATE SEQUENCE SEQ_LECTURE;

CREATE TABLE TBL_LECTURE(
	LECTURE_NUMBER NUMBER CONSTRAINT PK_LECTURE PRIMARY KEY,
	LECTURE_TITLE VARCHAR(500),
	LECTURE_CATEGORY VARCHAR(500),
	LECTURE_CONTENT VARCHAR(500),
	LECTURE_DATE DATE,
	LECTURE_APPLY_NUMBER VARCHAR(500),
	LECTURE_MAXIMUM_NUMBER VARCHAR2(500),
	LECTURE_STATUS VARCHAR(500),
	TEACHER_NUMBER NUMBER,
   CONSTRAINT FK_LECTURE_TEACHER FOREIGN KEY (TEACHER_NUMBER) REFERENCES TBL_TEACHER(TEACHER_NUMBER),
   PLACE_NUMBER NUMBER,
   CONSTRAINT FK_LECTURE_PLACE FOREIGN KEY (PLACE_NUMBER) REFERENCES TBL_PLACE(PLACE_NUMBER)
);

ALTER TABLE TBL_LECTURE DROP COLUMN LECTURE_APPLY_NUMBER;
ALTER TABLE TBL_LECTURE DROP COLUMN LECTURE_END_TIME;
ALTER TABLE TBL_LECTURE ADD LECTURE_APPLY_NUMBER NUMBER DEFAULT 0;

SELECT * FROM TBL_LECTURE;


/*강의 첨부파일 테이블*/
CREATE SEQUENCE SEQ_LECTURE_FILE;

CREATE TABLE TBL_LECTURE_FILE(
	LECTURE_FILE_NUMBER NUMBER CONSTRAINT PK_LECTURE_FILE PRIMARY KEY,
	LECTURE_FILE_NAME VARCHAR(500),
	LECTURE_FILE_UPLOAD_PATH VARCHAR(500),
	LECTURE_FILE_UUID VARCHAR(500),
	LECTURE_NUMBER NUMBER,
   CONSTRAINT FK_LECTURE_FILE FOREIGN KEY (LECTURE_NUMBER) REFERENCES TBL_LECTURE(LECTURE_NUMBER)
);


/*강의 섬네일 테이블*/
CREATE SEQUENCE SEQ_LECTURE_THUMBNAIL;

CREATE TABLE TBL_LECTURE_THUMBNAIL(
	LECTURE_THUMBNAIL_NUMBER NUMBER CONSTRAINT PK_LECTURE_TUMBNAIL PRIMARY KEY,
	LECTURE_THUMBNAIL_NAME VARCHAR(500),
	LECTURE_THUMBNAIL_UPLOAD_PATH VARCHAR(500),
	LECTURE_THUMBNAIL_UUID VARCHAR(500),
	LECTURE_NUMBER NUMBER,
   CONSTRAINT FK_LECTURE_THUMBNAIL FOREIGN KEY (LECTURE_NUMBER) REFERENCES TBL_LECTURE(LECTURE_NUMBER)
);


/*강의 공지 테이블*/
CREATE SEQUENCE SEQ_LECTURE_NOTICE;

CREATE TABLE TBL_LECTURE_NOTICE(
	LECTURE_NOTICE_NUMBER NUMBER CONSTRAINT PK_LECTURE_NOTICE PRIMARY KEY,
	LECTURE_NOTICE_TITLE VARCHAR(500),
	LECTURE_NOTICE_CONTENT VARCHAR(500),
	LECTURE_NOTICE_DATE DATE DEFAULT SYSDATE,
	LECTURE_NUMBER NUMBER,
   CONSTRAINT FK_LECTURE_NOTICE FOREIGN KEY (LECTURE_NUMBER) REFERENCES TBL_LECTURE(LECTURE_NUMBER)
);


/*강의 신청 테이블*/
CREATE SEQUENCE SEQ_APPLY_LECTURE;

CREATE TABLE TBL_APPLY_LECTURE(
	APPLY_LECTURE_NUMBER NUMBER CONSTRAINT PK_APPLY_LECTURE PRIMARY KEY,
	USER_NUMBER NUMBER,
   CONSTRAINT FK_APPLY_USER FOREIGN KEY (USER_NUMBER) REFERENCES TBL_USER(USER_NUMBER),
   LECTURE_NUMBER NUMBER,
   CONSTRAINT FK_APPLY_LECTURE FOREIGN KEY (LECTURE_NUMBER) REFERENCES TBL_LECTURE(LECTURE_NUMBER)
);



/*수강후기 테이블*/
CREATE SEQUENCE SEQ_REVIEW;

CREATE TABLE TBL_REVIEW(
	REVIEW_NUMBER NUMBER CONSTRAINT PK_REVIEW PRIMARY KEY,
	REVIEW_TITLE VARCHAR(500),
	REVIEW_CONTENT VARCHAR(500),
	REVIEW_REGISTER_DATE DATE DEFAULT SYSDATE,
	REVIEW_MODIFY_DATE DATE DEFAULT SYSDATE,
	LECTURE_NUMBER NUMBER,
   CONSTRAINT FK_REVIEW FOREIGN KEY (LECTURE_NUMBER) REFERENCES TBL_LECTURE(LECTURE_NUMBER)
);


/*강의 요청 테이블*/
CREATE SEQUENCE SEQ_REQUEST;

CREATE TABLE TBL_REQUEST(
	REQUEST_NUMBER NUMBER CONSTRAINT PK_REQUEST PRIMARY KEY,
	REQUEST_TITLE VARCHAR(500),
	REQUEST_CATEGORY VARCHAR(500),
	REQUEST_CONTENT VARCHAR(500),
	REQUEST_REGISTER_DATE DATE DEFAULT SYSDATE,
	REQUEST_MODIFY_DATE DATE DEFAULT SYSDATE,
	USER_NUMBER NUMBER,
   CONSTRAINT FK_REQUEST FOREIGN KEY (USER_NUMBER) REFERENCES TBL_USER(USER_NUMBER)
);


/*강의 요청 댓글 테이블*/
CREATE SEQUENCE SEQ_REQUEST_COMMENT;

CREATE TABLE TBL_REQUEST_COMMENT(
	REQUEST_COMMENT_NUMBER NUMBER CONSTRAINT PK_REQUEST_COMMENT PRIMARY KEY,
	REQUEST_COMMENT_CONTENT VARCHAR(500),
	USER_NUMBER NUMBER,
   CONSTRAINT FK_COMMENT_USER FOREIGN KEY (USER_NUMBER) REFERENCES TBL_USER(USER_NUMBER),
   REQUEST_NUMBER NUMBER,
   CONSTRAINT FK_COMMENT_REQUEST FOREIGN KEY (REQUEST_NUMBER) REFERENCES TBL_REQUEST(REQUEST_NUMBER)
);


/*강의 요청 좋아요 테이블*/
CREATE SEQUENCE SEQ_REQUEST_HEART;

CREATE TABLE TBL_REQUEST_HEART(
	REQUEST_HEART_NUMBER NUMBER CONSTRAINT PK_REQUEST_HEART PRIMARY KEY,
	USER_NUMBER NUMBER,
   CONSTRAINT FK_HEART_USER FOREIGN KEY (USER_NUMBER) REFERENCES TBL_USER(USER_NUMBER),
   REQUEST_NUMBER NUMBER,
   CONSTRAINT FK_HEART_REQUEST FOREIGN KEY (REQUEST_NUMBER) REFERENCES TBL_REQUEST(REQUEST_NUMBER)
);


/*공지 테이블*/
CREATE SEQUENCE SEQ_NOTICE;

CREATE TABLE TBL_NOTICE(
	NOTICE_NUMBER NUMBER CONSTRAINT PK_NOTICE PRIMARY KEY,
	NOTICE_TITLE VARCHAR2(500),
	NOTICE_CONTENT VARCHAR2(500),
	NOTICE_DATE DATE DEFAULT SYSDATE
);